name: dearplant
description: This is the demo for chat app by Flutter
environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.1.0
  firebase_auth: ^1.1.3
  google_sign_in: ^5.0.2
  cloud_firestore: ^1.0.7
  fluttertoast: ^8.0.6
  image_picker: ^0.7.4
  shared_preferences: ^2.0.5
  firebase_storage: ^8.0.5
  cached_network_image: ^3.0.0
  cupertino_icons: ^1.0.2
  flutter_blue: ^0.8.0
  assets_audio_player: ^3.0.3+2
  intl: ^0.17.0
  firebase_messaging: ^9.1.3
  flutter_local_notifications: ^5.0.0+4
  photo_view: ^0.11.1
  get: ^4.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/high_quality/
    - assets/sounds/
    - images/img_not_available.jpeg
    - images/mimi1.gif
    - images/mimi2.gif
    - images/mimi3.gif
    - images/mimi4.gif
    - images/mimi5.gif
    - images/mimi6.gif
    - images/mimi7.gif
    - images/mimi8.gif
    - images/mimi9.gif
    - images/water_over.png
    - images/humid_over.png
    - images/love.png
    - images/sun_below.png
    - images/sun_over.png
    - images/water_below.png
    - images/main2.jpg
